
import './App.css';
import { useEffect, useRef, useState } from "react";
import { StrudelMirror } from '@strudel/codemirror';
import { cpm, evalScope } from '@strudel/core';
import { drawPianoroll } from '@strudel/draw';
import { initAudioOnFirstClick } from '@strudel/webaudio';
import { transpiler } from '@strudel/transpiler';
import { getAudioContext, webaudioOutput, registerSynthSounds } from '@strudel/webaudio';
import { registerSoundfonts } from '@strudel/soundfonts';
import { stranger_tune } from './tunes';
import console_monkey_patch, { getD3Data } from './console-monkey-patch';
//UI Components being used 
import DjControls from './components/DJControls';
import PreProcessTextBody from './components/PreProcessTextBody';
import D3Graph from './components/D3Graph';
//image logo appearing on page
import strudelImage from './icons/strudel_icon.png';
let globalEditor = null;

const handleD3Data = (event) => {
    console.log(event.detail);
};

export default function StrudelDemo() {

    const hasRun = useRef(false);

    //defined two variables which are now going to be used for managing play and stop buttons 
    const handlePlay = () => {
        //Plays the code
        globalEditor.evaluate();
        //when being played, it sets the state to true, 
        setIsPlaying(true);
    }

    const handleStop = () => {
        globalEditor.stop();
        //when music is paused, it changes the state 
        setIsPlaying(false);
    }
    const [songText, setSongText] = useState(stranger_tune)

    const [volume, setVolume] = useState(0.5);

    //for tracking where music is playing or not
    const [isPlaying, setIsPlaying] = useState(false);

    //for the strudel data (returned through .log) to handle its values 
    const [graphData, setGraphData] = useState([]);
    useEffect(() => {
        
        if (!hasRun.current) {
            document.addEventListener("d3Data", handleD3Data);
            console_monkey_patch();
            hasRun.current = true;
            //Code copied from example: https://codeberg.org/uzu/strudel/src/branch/main/examples/codemirror-repl
            //init canvas
            const canvas = document.getElementById('roll');
            canvas.width = canvas.width * 2;
            canvas.height = canvas.height * 2;
            const drawContext = canvas.getContext('2d');
            const drawTime = [-2, 2]; // time window of drawn haps
            globalEditor = new StrudelMirror({
                defaultOutput: webaudioOutput,
                getTime: () => getAudioContext().currentTime,
                transpiler,
                root: document.getElementById('editor'),
                drawTime,
                onDraw: (haps, time) => drawPianoroll({ haps, time, ctx: drawContext, drawTime, fold: 0 }),
                prebake: async () => {
                    initAudioOnFirstClick(); // needed to make the browser happy (don't await this here..)
                    const loadModules = evalScope(
                        import('@strudel/core'),
                        import('@strudel/draw'),
                        import('@strudel/mini'),
                        import('@strudel/tonal'),
                        import('@strudel/webaudio'),
                    );
                    await Promise.all([loadModules, registerSynthSounds(), registerSoundfonts()]);
                },
            }); 
            document.getElementById('proc').value = stranger_tune
        }
        if (globalEditor) {
            //updates the strudel editor with new code after using a feature(dj buttons to change the rhythm)
            globalEditor.setCode(songText);
            //below restart the strudel editor with new code if the music is playing 
            if (isPlaying) {
                //here, it stops old music(before pressing any dj buttons), and starts the new music(afte rpressing dj butons)
                globalEditor.evaluate();
            }
        }
//runs the whole code above(function), when songText value and isPlaying value changes, everytime.  
}, [songText, isPlaying]);

    //bellow useEffect is for the D3 graph, as it runs only once when component first loads
    useEffect(() => {
        //getting the data generated by strudel
        const interval = setInterval(() => {
            const StrudelData = getD3Data()
            //updating the graph with new data(because of spread "...")
            setGraphData([...StrudelData])
            //console.log(StrudelData);
        //runs every 200 ms
        }, 200)
        //for preventing old intervals from running
        return () => clearInterval(interval);
    }, [])
    
    return (
        <div className="AppBody">
        <nav className="navbar navbar-dark bg-dark ">
            <a className="navbar-brand fs-1" ><b><i>Strudel Demo</i></b></a>
            <div className="strudellogo" >
                <img className="strudelAnimation" src={strudelImage} alt="Strudel Icon" style={{ width: '50px' }}></img>
            </div>
        </nav>
        <main>
            <div className="container-fluid">
                <div className="row g-4 p-5 ">
                    <div className="col-sm-7" style={{ maxHeight: '50vh', overflowY: 'auto' }}>
                        <div className="card">
                                <div className="card-body">
                                    {/* PreProcessTextBody that has the song text and calling the on change event to store the text typed by user into the state(using setState) */}
                                <PreProcessTextBody defaultValue={songText} onChange={(e) => setSongText(e.target.value)} />
                            </div>
                        </div>
                    </div>
                        <div className="col-sm-5" style={{ maxHeight: '50vh' }}>
                            <div className="card text-center" id="djControls" style={{ boxShadow: " 5px 10px rgba(0,0,0,0.6)" }}>
                                <div className="card-header fs-1"><b>DJ Controls</b></div>
                                <div className="card-body" >
                                    <h5 className="card-title"><b>Change Cpm</b></h5>
                                    {/*Calling DJCOntrols that has all the features, passing multiple props as their state gets updated inside DjControls*/}
                                    <DjControls songText={songText} setSongText={setSongText} volume={volume} setVolume={setVolume} onPlay={handlePlay} onStop={handleStop} />
                                </div>
                            </div>
                        </div>
                </div>
                <div className="row g-4 p-5">
                    <div className="col-sm-7 " style={{ maxHeight: '50vh', overflowY: 'auto' }}>
                        <div id="editor" />
                        <div id="output" />
                        </div>
                        <div className="col-mt-2 d-flex justify-content-center">
                            <div><canvas id="roll" ></canvas></div>  
                        </div>
                    </div>
                   {/*Calling the D3 graph component and passing in the prop= graphData*/}
                    <div><D3Graph strudelData={graphData} /> </div>
            </div>
          
        </main >
        <footer className="footer" role="contentinfo">
            <div className="footer-content" >
                <p className="footer-text">&copy; 2025 Strudel Demo. All rights reserved</p>
            </div>
        </footer>
    </div >
);


}